FROM python:3.7
WORKDIR /var/nameko/
ADD ./task/requirements.txt /var/nameko/requirements.txt
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y netcat
ADD ./task /var/nameko/
ADD ./lib/ /var/nameko/
RUN chmod +x /var/nameko/run.sh
EXPOSE 8160
CMD /var/nameko/run.sh;
